<div id="mobile-menu-logo-wrapper" class="visible-xs visible-sm">
	<div class="mobile-menu container">
		<div class="row">
			<div class="col-md-12">
				<a href="index.html" class="logo"></a>
				<div class="toggle-menu-container pull-right">					
					<div class="toggle-menu">
						<a href="javascript:void(0)"> 
							<span class="nav-bar"></span> 
							<span class="nav-bar"></span> 
							<span class="nav-bar"></span> 
						</a> 
					</div>
				</div>				
			</div>
		</div>
	</div>			
	<div class="mobile-nav-container" class="visible-xs visible-sm">
		<!-- <div class="container"> -->
			<!-- <div class="row">
				<div class="col-md-12"> -->
					<ul class="mobile-nav">
						<li><a href="#">Profile</a></li>
						<li class="has-child">
							<a href="#" class="sub-nav-toggle">Portfolio</a>
							<ul class="mobile-nav-child">
								<li><a href="portfolio.html#all">All Featured</a></li>
								<li><a href="portfolio.html#signaturebyblink">Signature by Blink</a></li>
								<li><a href="portfolio.html#resorts">Resorts</a></li>
								<li><a href="portfolio.html#hotels">Hotels</a></li>
								<li><a href="portfolio.html#masterplanning">Master Planning</a></li>
								<li><a href="portfolio.html#interiordesign">Interior Design</a></li>
								<li><a href="portfolio.html#branddesign">Brand Design</a></li>
								<li><a href="portfolio.html#buildingdesign">Building Design</a></li>
							</ul>
						</li>
						<li class="has-child">
							<a href="#" class="sub-nav-toggle">Stories</a>
							<ul class="mobile-nav-child">
								<li><a href="story.html">Fairmont Sanur Beach</a></li>
								<li><a href="story.html">Regent Phuket</a></li>
								<li><a href="story.html">Jumeirah Dhevanafushi</a></li>
								<li><a href="story.html">Hilton Goa</a></li>
								<li><a href="story.html">Hyatt Jeju</a></li>
								<li><a href="story.html">Six Senses Uluwata</a></li>							
							</ul>
						</li>
						<li><a href="insights.html">Insights</a></li>
						<li><a href="#">Careers</a></li>
						<li><a href="#">News</a></li>
						<li><a href="#">Contact</a></li>
					</ul>	
				<!-- </div>
			</div>	 -->	
		<!-- </div> -->
	</div>
</div>

