<div id="carousel" class="slider-wrapper carousel slide" data-ride="carousel">

	<!-- Wrapper for slides -->
	<div class="carousel-inner" role="listbox">
		<div class="item bg contact-us-bg-1 active">
			<div class="carousel-caption">
				<div class="caption-text">
					<h5 class="pulse">contact us</h5>
					<h1>Get in touch with us</h1>
					<div class="seperator-line"></div>
					<p class="hidden-xs hidden-sm">Lorem ipsum dolor sit amet consectetuer adipiscing aenean commodo dolor aenean massa there sociis natoque penati itheru magnis.</p>
					<p class="visible-xs visible-sm">Lorem ipsum dolor sit amet consectetuer adipiscing aenean commodo dolor aenean massa there sociis natoque penati itheru magnis.</p>
				</div>				
			</div>
		</div>
		<!-- <div class="item bg bg2"></div>
		<div class="item bg bg2"></div>
		<div class="item bg bg2"></div> -->
	</div>

	<a href="#content-wrapper" class="scroll-to-content">	
		<div class="arrow">
			<i class="fa fa-chevron-down first"></i>
			<i class="fa fa-chevron-down second"></i>
			<i class="fa fa-chevron-down third"></i>
		</div>
	</a>

	<!-- Indicators -->
  	<!-- <ol class="carousel-indicators">
	    <li data-target="#carousel" data-slide-to="0" class="active"></li>
	    <li data-target="#carousel" data-slide-to="1"></li>
	    <li data-target="#carousel" data-slide-to="3"></li>
	    <li data-target="#carousel" data-slide-to="4"></li>
  	</ol> -->

</div>