
		<footer id="footer-wrapper" class="fixed-footer"><!-- container-fluid -->
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<div class="pull-left tweet">
							<ul>
								<li><a href="contact-us.html">BANGKOK</a></li>
								<li><a href="contact-us.html">NEW DELHI</a></li>
								<li><a href="contact-us.html">SINGAPORE</a></li>
								<li><a href="contact-us.html">SHANGHAI</a></li>
							</ul>
							<!--  legends of luxury... @Blinkdesigngroup -->
						</div>
						<div class="pull-right sharing hidden-xs hidden-sm">
							<p>&copy; 2016 Blink Design Group. All Rights Reserved.</p>
						</div>
					</div>
				</div>
			</div>
		</footer>

</div><!-- page wrapper end -->