<div id="mailing-list-wrapper" class="fixed-footer">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="left each-column">						
						<h4>Follow Us</h4>
						<ul>
							<li><a href="#"><i class="fa fa-instagram"></i></a></li>
							<li><a href="#"><i class="fa fa-pinterest"></i></a></li>
							<li><a href="#"><i class="fa fa-facebook"></i></a></li>
							<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
							<li><a href="#"><i class="fa fa-twitter"></i></a></li>
							<li><a href="#"><i class="fa fa-google-plus"></i></a></li>						
						</ul>
					</div>
					<div class="middle each-column">
						<ul>
							<li><a href="#">Profile</a></li>
							<li><a href="#">Services</a></li>
							<li><a href="#">Portfolio</a></li>
							<li><a href="#">Services</a></li>
						</ul>
						<ul>
							<li><a href="story.html">Stories</a></li>
							<li><a href="clients.html">Clients</a></li>
							<li><a href="#">News</a></li>
							<li><a href="#">Careers</a></li>
						</ul>
						<ul>
							<li><a href="#">Careers</a></li>
							<li><a href="#">Contact Us</a></li>
							<li><a href="#">Privacy Policy</a></li>
							<li><a href="#">Terms of Use</a></li>							
						</ul>
					</div>
					<div class="right each-column">
						<div class="text-content">
							<h3>Join Our Mailing List</h3>
							<p>Subscribe to our newsletter and stay updated <br> with our latest work and news.</p>
						</div>
						<div class="input">
							<input type="text" name="subscribe" placeholder="Enter your email address" />
							<i class="fa fa-angle-right"></i>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
