<div id="mailing-list-wrapper" class="fixed-footer">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="left each-column hidden-xs hidden-sm">						
						<h4>thinkBLINK COMMUNITIES</h4>
						<ul>
							<!-- <li><a href="#"><i class="fa fa-instagram"></i></a></li>
							<li><a href="#"><i class="fa fa-pinterest"></i></a></li> -->
							<li><a target="_blank" href="https://www.facebook.com/BLINK-Design-Group-1504843613064866/"><i class="fa fa-facebook"></i></a></li>
							<li><a target="_blank" href="https://www.linkedin.com/company/blink-design-group"><i class="fa fa-linkedin"></i></a></li>
							<!-- <li><a href="#"><i class="fa fa-twitter"></i></a></li>
							<li><a href="#"><i class="fa fa-google-plus"></i></a></li>						 -->
						</ul>
					</div>
					<div class="middle footer-links each-column">
						<ul>
							<li><a href="profile.html">Profile</a></li>
							<!-- <li><a href="#">Services</a></li> -->
							<li><a href="portfolio.html">Portfolio</a></li>
							<!-- <li><a href="story.html">Stories</a></li> -->
						</ul>
						<ul>							
							<li><a href="insights.html">Insights</a></li>
							<li><a href="news.html">News</a></li>							
						</ul>
						<ul>
							
							<li><a href="contact-us.html">Contact Us</a></li>
							<li><a href="careers.html">Careers</a></li>
							<!-- <li><a href="#">Terms of Use</a></li>							 -->
						</ul>
					</div>
					<div class="right each-column">
						<div class="text-content">
							<h3>thinkBLINK NEWS</h3>
							<p>Subscribe to our newsletter and stay updated <br> with our latest work and news.</p>
						</div>
						<div class="input">
							<input type="text" id="subscribe_input" name="subscribe" placeholder="Enter your email address" />
							<a href="#" class="subscribe"><i class="fa fa-angle-right"></i></a>
							<div class="loading"></div>					
						</div>
					</div>
					<div class="clear"></div>
					<div class="left follow-us each-column visible-xs visible-sm">						
						<h4>Follow Us</h4>
						<ul>
							<li><a href="#"><i class="fa fa-instagram"></i></a></li>
							<li><a href="#"><i class="fa fa-pinterest"></i></a></li>
							<li><a href="#"><i class="fa fa-facebook"></i></a></li>
							<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
							<li><a href="#"><i class="fa fa-twitter"></i></a></li>
							<li><a href="#"><i class="fa fa-google-plus"></i></a></li>						
						</ul>

						<p class="visible-xs visible-sm">&copy; 2015 Blink Design Group. All Rights Reserved.</p>
					</div>
				</div>
			</div>
		</div>
	</div>
