<div id="menu-logo-wrapper" class="animated slideInDown hidden-xs hidden-sm">
	
	<div class="main-menu">
		<a href="index.html" class="logo"></a>
		<div class="sidebar-nav pull-right">
			<ul class="main-nav">
				<li><a href="profile.html">Profile</a></li>
				<li>
					<a href="portfolio.html" class="">Portfolio</a>
					<!-- <a href="#" class="has-child">Portfolio</a> -->
					<!-- <div class="sub-nav-container portfolio-sub-nav">
						<ul class="sub-nav-1 sub-nav">
							<li><a href="portfolio.html#all">All Featured</a></li>
							<li><a href="portfolio.html#signaturebyblink">Signature by Blink</a></li>									
							<li><a href="portfolio.html#resorts">Resorts</a></li>
							<li><a href="portfolio.html#hotels">Hotels</a></li>
						</ul>
						<ul class="sub-nav-2 sub-nav">
							<li><a href="portfolio.html#masterplanning">Master Planning</a></li>
							<li><a href="portfolio.html#interiordesign">Interior Design</a></li>																		
							<li><a href="portfolio.html#branddesign">Brand Design</a></li>
							<li><a href="portfolio.html#buildingdesign">Building Design</a></li>																		
						</ul>
					</div> -->
				</li>
				<!-- <li>
					<a href="#" class="has-child">Stories</a>
					<div class="sub-nav-container">
						<ul class="sub-nav-1 sub-nav">
							<li><a href="story-fairmont-sanur-beach.html">Fairmont Sanur Beach</a></li>
							<li><a href="story-regent-phuket.html">Regent Phuket</a></li>									
							<li><a href="story-jumeirah-dhevanafushi.html">Jumeirah Dhevanafushi</a></li>
							<li><a href="story-hilton-goa.html">Hilton Goa</a></li>
						</ul>
						<ul class="sub-nav-2 sub-nav">
							<li><a href="story-hyatt-jeju.html">Hyatt Jeju</a></li>
							<li><a href="story-six-senses-uluwata.html">Six Senses Uluwata</a></li>																		
						</ul>
					</div>					
				</li> -->
				<li><a href="insights.html">Insights</a></li>
				<li><a href="careers.html">Careers</a></li>
				<li><a href="news.html">News</a></li>						
				<li><a href="contact-us.html">Contact</a></li>
				<li>
					<a href="#" class="site-search"><i class="fa fa-search"></i></a>
					<form action="search.html">
						<input type="text" name="q" id="search_input" required>
						<a href="#" class="close-search"><i class="fa fa-times"></i></a>
					</form>
				</li>
			</ul>				
		</div>				
	</div>	

</div>