<div id="mobile-menu-logo-wrapper" class="visible-xs visible-sm">
	<div class="mobile-menu container">
		<div class="row">
			<div class="col-md-12">
				<a href="index.html" class="logo"></a>
				<div class="toggle-menu-container pull-right">					
					<div class="toggle-menu">
						<a href="javascript:void(0)"> 
							<span class="nav-bar"></span> 
							<span class="nav-bar"></span> 
							<span class="nav-bar"></span> 
						</a> 
					</div>
				</div>
				<a href="#" class="mobile-search pull-right"><i class="fa fa-search"></i></a>			
			</div>
		</div>
	</div>			
	<div class="mobile-nav-container" class="visible-xs visible-sm">
		<!-- <div class="container"> -->
			<!-- <div class="row">
				<div class="col-md-12"> -->
					<ul class="mobile-nav">
						<li><a href="#">Profile</a></li>
						<li class="has-child">
							<a href="#" class="sub-nav-toggle">Portfolio</a>
							<ul class="mobile-nav-child">
								<li><a href="portfolio.html#all">All Featured</a></li>
								<li><a href="portfolio.html#signaturebyblink">Signature by Blink</a></li>
								<li><a href="portfolio.html#resorts">Resorts</a></li>
								<li><a href="portfolio.html#hotels">Hotels</a></li>
								<li><a href="portfolio.html#masterplanning">Master Planning</a></li>
								<li><a href="portfolio.html#interiordesign">Interior Design</a></li>
								<li><a href="portfolio.html#branddesign">Brand Design</a></li>
								<li><a href="portfolio.html#buildingdesign">Building Design</a></li>
							</ul>
						</li>
						<li class="has-child">
							<a href="#" class="sub-nav-toggle">Stories</a>
							<ul class="mobile-nav-child">
								<li><a href="story.html">Fairmont Sanur Beach</a></li>
								<li><a href="story.html">Regent Phuket</a></li>
								<li><a href="story.html">Jumeirah Dhevanafushi</a></li>
								<li><a href="story.html">Hilton Goa</a></li>
								<li><a href="story.html">Hyatt Jeju</a></li>
								<li><a href="story.html">Six Senses Uluwata</a></li>							
							</ul>
						</li>
						<li><a href="insights.html">Insights</a></li>
						<li><a href="careers.html">Careers</a></li>
						<li><a href="#">News</a></li>
						<li><a href="contact-us.html">Contact</a></li>
					</ul>	
				<!-- </div>
			</div>	 -->	
		<!-- </div> -->
	</div>
	<div class="mobile-search-box-container container">
		<div class="row">
			<div class="col-md-12">
				<div class="search-box-title">
					<div class="title">
						<h4>Search Blink</h4>
						<p>Access our portfolio of projects.</p>
					</div>
					<a href="#" class="close-btn"></a>
				</div>
				<div class="clear"></div>
				<div class="search-box-content">
					<input type="text" name="search" >

					<div class="related-result">
						<ul>
							<li class="related-result-header">Projects</li>
							<li><a href="#">Doubletree Sanya</a></li>
							<li><a href="#">Hilton Goa</a></li>
							<li><a href="#">Benxi Doubletree by Hilton</a></li>
							<li><a href="#">Renaissance & Courtyard by Marriott</a></li>
							<li><a href="#">Marriott Xiang Shui Bay</a></li>
							<li><a href="#">Dongqian Lake Ningbo</a></li>
							<li><a href="#">Marriott Wenchang</a></li>
							<li><a href="#">Hilton Fengxian</a></li>
						</ul>
					</div>
				</div>	
			</div>
		</div>		
	</div>
</div>

