<div id="mobile-menu-logo-wrapper" class="visible-xs visible-sm">
	<div class="mobile-menu container">
		<div class="row">
			<div class="col-md-12">
				<a href="index.html" class="logo"></a>
				<div class="toggle-menu-container pull-right">					
					<div class="toggle-menu">
						<a href="javascript:void(0)"> 
							<span class="nav-bar"></span> 
							<span class="nav-bar"></span> 
							<span class="nav-bar"></span> 
						</a> 
					</div>
				</div>				
			</div>
		</div>
	</div>			
	<div class="mobile-nav-container" class="visible-xs visible-sm">
		<!-- <div class="container"> -->
			<!-- <div class="row">
				<div class="col-md-12"> -->
					<ul class="mobile-nav">
						<li><a href="#">Profile</a></li>
						<li class="has-child">
							<a href="#" class="sub-nav-toggle">Portfolio</a>
							<ul class="mobile-nav-child">
								<li><a href="#">All Featured</a></li>
								<li><a href="#">Signature by Blink</a></li>
								<li><a href="#">Resorts</a></li>
								<li><a href="#">Hotels</a></li>
								<li><a href="#">Master Planning</a></li>
								<li><a href="#">Interior Design</a></li>
								<li><a href="#">Brand Design</a></li>
								<li><a href="#">Building Design</a></li>
							</ul>
						</li>
						<li class="has-child">
							<a href="#" class="sub-nav-toggle">Stories</a>
							<ul class="mobile-nav-child">
								<li><a href="#">Fairmont Sanur Beach</a></li>
								<li><a href="#">Regent Phuket</a></li>
								<li><a href="#">Jumeirah Dhevanafushi</a></li>
								<li><a href="#">Hilton Goa</a></li>
								<li><a href="#">Hyatt Jeju</a></li>
								<li><a href="#">Six Senses Uluwata</a></li>							
							</ul>
						</li>
						<li><a href="#">Insights</a></li>
						<li><a href="#">Careers</a></li>
						<li><a href="#">News</a></li>
						<li><a href="#">Contact</a></li>
					</ul>	
				<!-- </div>
			</div>	 -->	
		<!-- </div> -->
	</div>
</div>

