<div id="carousel" class="slider-wrapper carousel slide carousel-resize-on-mobile" data-ride="carousel">

	<!-- Wrapper for slides -->
	<div class="carousel-inner" role="listbox">
		<div class="item bg project-raycom-bg-1 active"></div>
		<div class="item bg project-raycom-bg-2"></div>
		<div class="item bg project-raycom-bg-3"></div>
	</div>

	<a href="#content-wrapper" class="scroll-to-content">	
		<div class="arrow-big"></div>
		<!-- <div class="arrow">
			<i class="fa fa-chevron-down first"></i>
			<i class="fa fa-chevron-down second"></i>
			<i class="fa fa-chevron-down third"></i>
		</div> -->
	</a>

	<!-- Indicators -->
  	<ol class="carousel-indicators">
	    <li data-target="#carousel" data-slide-to="0" class="active"></li>
	    <li data-target="#carousel" data-slide-to="1"></li>
	    <li data-target="#carousel" data-slide-to="2"></li>
  	</ol>

</div>