<div id="carousel" class="slider-wrapper carousel slide" data-ride="carousel">

	<!-- <div class="logo">bdg</div> -->

	<!-- Wrapper for slides -->
	<div class="carousel-inner" role="listbox">
		<div class="item bg bg1 active">			
			<div class="carousel-caption">
				<div class="caption-text">
					<h5 class="pulse">Who We Are</h5>
					<h1>asia born internationally acclaimed</h1>
					<div class="seperator-line"></div>
					<p class="hidden-xs hidden-sm">Lorem ipsum dolor sit amet consectetuer adipiscing elit aenean commodo <br>dolor aenean massa there sociis natoque penati itheru bus et magnis.</p>
					<p class="visible-xs visible-sm">Lorem ipsum dolor sit amet consectetuer adipiscing elit aenean commodo dolor aenean massa there sociis natoque penati itheru bus et magnis.</p>
				</div>				
			</div>				
		</div>
		<div class="item bg bg2">			
			<div class="carousel-caption">
				<div class="caption-text">
					<h5>Who We Are 2</h5>
					<h1>asia born internationally acclaimed</h1>
					<div class="seperator-line"></div>
					<p class="hidden-xs hidden-sm">Lorem ipsum dolor sit amet consectetuer adipiscing elit aenean commodo <br>dolor aenean massa there sociis natoque penati itheru bus et magnis.</p>
					<p class="visible-xs visible-sm">Lorem ipsum dolor sit amet consectetuer adipiscing elit aenean commodo dolor aenean massa there sociis natoque penati itheru bus et magnis.</p>
				</div>				
			</div>				
		</div>
		<div class="item bg bg3">			
			<div class="carousel-caption">
				<div class="caption-text">
					<h5>Who We Are 3</h5>
					<h1>asia born internationally acclaimed</h1>
					<div class="seperator-line"></div>
					<p class="hidden-xs hidden-sm">Lorem ipsum dolor sit amet consectetuer adipiscing elit aenean commodo <br>dolor aenean massa there sociis natoque penati itheru bus et magnis.</p>
					<p class="visible-xs visible-sm">Lorem ipsum dolor sit amet consectetuer adipiscing elit aenean commodo dolor aenean massa there sociis natoque penati itheru bus et magnis.</p>
				</div>				
			</div>				
		</div>
		<div class="item bg bg4">			
			<div class="carousel-caption">
				<div class="caption-text">
					<h5>Who We Are 4</h5>
					<h1>asia born internationally acclaimed</h1>
					<div class="seperator-line"></div>
					<p class="hidden-xs hidden-sm">Lorem ipsum dolor sit amet consectetuer adipiscing elit aenean commodo <br>dolor aenean massa there sociis natoque penati itheru bus et magnis.</p>
					<p class="visible-xs visible-sm">Lorem ipsum dolor sit amet consectetuer adipiscing elit aenean commodo dolor aenean massa there sociis natoque penati itheru bus et magnis.</p>
				</div>				
			</div>				
		</div>
	</div>

	<a href="#content-wrapper" class="scroll-to-content">	
		<div class="arrow">
			<i class="fa fa-chevron-down first"></i>
			<i class="fa fa-chevron-down second"></i>
			<i class="fa fa-chevron-down third"></i>
		</div>
	</a>

	<!-- Indicators -->
	  <ol class="carousel-indicators">
	    <li data-target="#carousel" data-slide-to="0" class="active"></li>
	    <li data-target="#carousel" data-slide-to="1"></li>
	    <li data-target="#carousel" data-slide-to="3"></li>
	    <li data-target="#carousel" data-slide-to="4"></li>
	  </ol>
</div>