
	<footer id="footer-wrapper" class="fixed-footer"><!-- container-fluid -->
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="pull-left tweet">
						<p><i class="fa fa-twitter"></i> @Interiordesign: Blink Design Group on what it's like working for legends of luxury... @Blinkdesigngroup</p>
					</div>
					<div class="pull-right sharing">
						<p>&copy; 2015 Blink Design Group. All Rights Reserved.</p>
					</div>
				</div>
			</div>
		</div>
	</footer>
</div><!-- page wrapper end -->