<!-- Mobile Viewport -->
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

<!-- Force IE to render best possible view -->
<meta http-equiv="X-UA-Compatible" content="IE=edge" />

<!-- FONT -->
<link href='https://fonts.googleapis.com/css?family=Merriweather:300italic|Open+Sans:400,300' rel='stylesheet' type='text/css'>

<!-- CSS -->
<link rel="stylesheet" href="css/vendors/bootstrap/bootstrap.min.css" />
<link rel="stylesheet" href="css/vendors/bootstrap/bootstrap-theme.min.css" />
<link rel="stylesheet" href="css/vendors/jquery-ui/jquery-ui.min.css" />
<link rel="stylesheet" href="css/font-awesome.min.css" />
<link rel="stylesheet" href="css/animate.min.css" />
<link rel="stylesheet" href="css/style.css" />
<link rel="stylesheet" href="css/mobile-style.css" />
<link rel="stylesheet" href="css/jquery.fullpage.min.css" />

<!-- JS -->
<script type="text/javascript" src="js/vendors/jquery/jquery-1.11.1.min.js"></script>
<script type="text/javascript" src="js/vendors/jquery/jquery-ui.min.js"></script>
<script type="text/javascript" src="js/vendors/bootstrap/bootstrap.min.js"></script>
<script type="text/javascript" src="js/plugins/imagesloaded.pkgd.min.js"></script>
<script type="text/javascript" src="js/plugins/isotope.pkgd.min.js"></script>
<script type="text/javascript" src="js/plugins/jquery.mousewheel.min.js"></script>
<script type="text/javascript" src="js/plugins/jquery.disablescroll.min.js"></script>

<script src="//cdnjs.cloudflare.com/ajax/libs/gsap/1.18.0/TimelineMax.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/gsap/1.18.0/TweenMax.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/gsap/1.18.0/TweenLite.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/gsap/1.18.0/plugins/ScrollToPlugin.min.js"></script>


<script type="text/javascript" src="js/main.js"></script>

