<div id="mailing-list-wrapper" class="fixed-footer">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="left each-column">
						<h3>Blink Design Group</h3>
						<h4>Follow Us</h4>
						<ul>
							<li><a href="#"><i class="fa fa-instagram"></i></a></li>
							<li><a href="#"><i class="fa fa-pinterest"></i></a></li>
							<li><a href="#"><i class="fa fa-facebook"></i></a></li>
							<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
							<li><a href="#"><i class="fa fa-twitter"></i></a></li>
							<li><a href="#"><i class="fa fa-google-plus"></i></a></li>						
						</ul>
					</div>
					<div class="middle each-column">
						<ul>
							<li><a href="#">Profile</a></li>
							<li><a href="#">Services</a></li>
							<li><a href="#">Portfolio</a></li>
							<li><a href="#">Services</a></li>
						</ul>
						<ul>
							<li><a href="#">Case Studies</a></li>
							<li><a href="#">Clients</a></li>
							<li><a href="#">News</a></li>
							<li><a href="#">Careers</a></li>
						</ul>
						<ul>
							<li><a href="#">Careers</a></li>
							<li><a href="#">Contact Us</a></li>
							<li><a href="#">Privacy Policy</a></li>
							<li><a href="#">Terms of Use</a></li>							
						</ul>
					</div>
					<div class="right each-column">
						<h3>Join Our Mailing List</h3>
						<p>Subscribe to our newsletter and stay updated with our latest work and news.</p>
						<input type="text" name="subscribe" placeholder="Enter your email address" />
					</div>
				</div>
			</div>
		</div>
	</div>
