<div id="menu-logo-wrapper" class="animated slideInDown">
	<!-- <div class="container">
		<div class="row">
			<div class="col-md-12"> -->
			<div class="main-menu">
				<a href="index.html" class="logo"></a>
				<div class="sidebar-nav pull-right">
					<ul class="main-nav">
						<li><a href="#">Profile</a></li>
						<li><a href="#">Portfolio</a></li>
						<li>
							<a href="#" class="has-child">Case Studies</a>
							<div id="sub-nav-container">
								<!-- <a href="#" class="by-categories">By Categoires <i class="fa fa-chevron-down"></i></a> -->

								<ul class="sub-nav-1 sub-nav">
									<li><a href="case-study.html">Fairmont Sanur Beach</a></li>
									<li><a href="case-study.html">Regent Phuket</a></li>									
									<li><a href="case-study.html">Jumeirah Dhevanafushi</a></li>
									<li><a href="case-study.html">Hilton Goa</a></li>
								</ul>
								<ul class="sub-nav-2 sub-nav">
									<li><a href="case-study.html">Hyatt Jeju</a></li>
									<li><a href="case-study.html">Six Senses Uluwata</a></li>																		
								</ul>
							</div>
							
						</li>
						<li><a href="clients.html">Clients</a></li>
						<li><a href="#">News</a></li>						
						<li><a href="#">Contact</a></li>
						<li><a href="#"><i class="fa fa-search"></i></a></li>
					</ul>				
				</div>
			</div>
			<!-- </div>
		</div>
	</div> -->			
</div>