<div id="menu-logo-wrapper" class="animated slideInDown">
	<!-- <div class="container">
		<div class="row">
			<div class="col-md-12"> -->
			<div class="main-menu">
				<a href="index.html" class="logo"></a>
				<div class="sidebar-nav pull-right">
					<ul class="main-nav">
						<li><a href="#">Profile</a></li>
						<li>
							<a href="#" class="has-child">Portfolio</a>
							<div class="sub-nav-container">
								<ul class="sub-nav-1 sub-nav">
									<li><a href="category.html">All Featured</a></li>
									<li><a href="category.html">Signature by Blink</a></li>									
									<li><a href="category.html">Resorts</a></li>
									<li><a href="category.html">Hotels</a></li>
								</ul>
								<ul class="sub-nav-2 sub-nav">
									<li><a href="category.html">Master Planning</a></li>
									<li><a href="category.html">Interior Design</a></li>																		
									<li><a href="category.html">Brand Design</a></li>
									<li><a href="category.html">Building Design</a></li>																		
								</ul>
							</div>
						</li>
						<li>
							<a href="#" class="has-child">Stories</a>
							<div class="sub-nav-container">
								<ul class="sub-nav-1 sub-nav">
									<li><a href="story.html">Fairmont Sanur Beach</a></li>
									<li><a href="story.html">Regent Phuket</a></li>									
									<li><a href="story.html">Jumeirah Dhevanafushi</a></li>
									<li><a href="story.html">Hilton Goa</a></li>
								</ul>
								<ul class="sub-nav-2 sub-nav">
									<li><a href="story.html">Hyatt Jeju</a></li>
									<li><a href="story.html">Six Senses Uluwata</a></li>																		
								</ul>
							</div>					
						</li>
						<li><a href="clients.html">Clients</a></li>
						<li><a href="#">News</a></li>						
						<li><a href="#">Contact</a></li>
						<li><a href="#"><i class="fa fa-search"></i></a></li>
					</ul>				
				</div>
			</div>
			<!-- </div>
		</div>
	</div> -->			
</div>