<div id="carousel" class="slider-wrapper carousel slide carousel-resize-on-mobile" data-ride="carousel">

	<!-- <div class="logo">bdg</div> -->

	<!-- Wrapper for slides -->
	<div class="carousel-inner" role="listbox">
		<div class="item bg clients-bg-1 active">			
			<!-- <div class="carousel-caption carousel-caption-with-text insights-caption">
				<div class="caption-text">
					<h5 class="pulse">hear our clients</h5>
					<h1>There can be as much value in the blink of an eye as in months of rational analysis.</h1>
					<div class="seperator-line"></div>
					<p>― Malcolm Gladwell, Blink: The Power of Thinking Without Thinking”</p>
				</div>				
			</div>				 -->
		</div>		
	</div>

	<a href="#content-wrapper" class="scroll-to-content">	
		<div class="arrow-big"></div>
		<!-- <div class="arrow">
			<i class="fa fa-chevron-down first"></i>
			<i class="fa fa-chevron-down second"></i>
			<i class="fa fa-chevron-down third"></i>
		</div> -->
	</a>

	<!-- Indicators -->
	  <!-- <ol class="carousel-indicators">
	    <li data-target="#carousel" data-slide-to="0" class="active"></li>
	    <li data-target="#carousel" data-slide-to="1"></li>
	    <li data-target="#carousel" data-slide-to="3"></li>
	    <li data-target="#carousel" data-slide-to="4"></li>
	  </ol> -->
</div>