<title>BLINK - Asia–born, Internationally Acclaimed Hotel and Resort Designers</title>
<meta name="description" content="BLINK is Asia-born and internationally acclaimed for distinctive, successful hotels and resorts for clients all over the world">
<meta name="keywords" content="Blink">

<!-- Mobile Viewport -->
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

<!-- Force IE to render best possible view -->
<meta http-equiv="X-UA-Compatible" content="IE=edge" />

<!-- FAVICON -->
<link rel="icon" href="images/icons/favicon.png" type="image/png" sizes="16x16">

<!-- FONT -->
<!-- <link href='https://fonts.googleapis.com/css?family=Merriweather:300italic|Open+Sans:400,300,700' rel='stylesheet' type='text/css'> -->
<!-- <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400,300,700' rel='stylesheet' type='text/css'> -->
<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,400italic,300,300italic,700' rel='stylesheet' type='text/css'>
<link rel="stylesheet" type="text/css" href="//cloud.typography.com/6413692/7416752/css/fonts.css" />

<!-- CSS -->
<link rel="stylesheet" href="css/vendors/bootstrap/bootstrap.min.css" />
<link rel="stylesheet" href="css/vendors/bootstrap/bootstrap-theme.min.css" />
<link rel="stylesheet" href="css/vendors/jquery-ui/jquery-ui.min.css" />
<link rel="stylesheet" href="css/font-awesome.min.css" />
<link rel="stylesheet" href="css/animate.min.css" />
<link rel="stylesheet" href="css/style.css" />
<link rel="stylesheet" href="css/mobile-style.css" />
<link rel="stylesheet" href="css/jquery.fullpage.min.css" />

<!-- JS -->
<script type="text/javascript" src="js/vendors/jquery/jquery-1.11.1.min.js"></script>
<script type="text/javascript" src="js/vendors/jquery/jquery-ui.min.js"></script>
<script type="text/javascript" src="js/vendors/jquery/jquery.mobile.custom.min.js"></script>
<script type="text/javascript" src="js/vendors/bootstrap/bootstrap.min.js"></script>
<script type="text/javascript" src="js/plugins/imagesloaded.pkgd.min.js"></script>
<script type="text/javascript" src="js/plugins/isotope.pkgd.min.js"></script>
<script type="text/javascript" src="//rawgit.com/metafizzy/isotope-packery/master/packery-mode.pkgd.js"></script>
<script type="text/javascript" src="js/plugins/jquery.mousewheel.min.js"></script>
<script type="text/javascript" src="js/plugins/jquery.disablescroll.min.js"></script>


<script src="//cdnjs.cloudflare.com/ajax/libs/gsap/1.18.0/TimelineMax.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/gsap/1.18.0/TweenMax.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/gsap/1.18.0/TweenLite.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/gsap/1.18.0/plugins/ScrollToPlugin.min.js"></script>


<script type="text/javascript" src="js/main.js"></script>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-669565-60', 'auto');
  ga('send', 'pageview');

</script>

