<div class="content-3">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="seperator"></div>
				<h5>Related Projects</h5>
			</div>
		</div>
	</div>
	<div class="container">
		<div class="row">
			<div class="col-md-12">																		
				<ul>
					<li>
						<div class="img-placeholder"><img src="images/content/projects/project-content-9.jpg" class="img-responsive" alt=""></div>
						<div class="caption-text">
							<h6>HILTON FENGHAI</h6>
							<p>Shanghai, China</p>
						</div>
					</li>
					<li>
						<div class="img-placeholder"><img src="images/content/projects/project-content-10.jpg" class="img-responsive" alt=""></div>
						<div class="caption-text">
							<h6>MARRIOTT WENCHANG</h6>
							<p>Shanghai, China</p>
						</div>
					</li>
					<li>
						<div class="img-placeholder"><img src="images/content/projects/project-content-11.jpg" class="img-responsive" alt=""></div>
						<div class="caption-text">
							<h6>REGENT PHUKET CAPE PANWA</h6>
							<p>Phuket, Thailand</p>
						</div>
					</li>
				</ul>							
			</div>
		</div>
	</div>
</div>