<div id="carousel" class="slider-wrapper carousel slide carousel-resize-on-mobile" data-ride="carousel">

	<!-- Wrapper for slides -->
	<div class="carousel-inner" role="listbox">
		<div class="item bg story-jumeirah-dhevanafushi-bg-1 active">
			<div id="blur-bg"></div>
			<div class="carousel-caption-2 hidden-sm hidden-xs">
				<h3>Jumeirah Dhevanfushi</h3>
				<ul>
					<li><span class="title">Location:</span><span class="content">Gaafu Alifu Atoll, Maldives</span></li>
					<li><span class="title">Category:</span><span class="content">Signature, Interior design, Building Design</span></li>
					<li><span class="title">Type:</span><span class="content">Hospitality</span></li>
				</ul>
			</div>	
		</div>
		<!-- <div class="item bg bg2"></div>
		<div class="item bg bg2"></div>
		<div class="item bg bg2"></div> -->
	</div>

	<a href="#content-wrapper" class="scroll-to-content">	
		<div class="arrow-big"></div>
		<!-- <div class="arrow">
			<i class="fa fa-chevron-down first"></i>
			<i class="fa fa-chevron-down second"></i>
			<i class="fa fa-chevron-down third"></i>
		</div> -->
	</a>

	<!-- Indicators -->
  	<!-- <ol class="carousel-indicators">
	    <li data-target="#carousel" data-slide-to="0" class="active"></li>
	    <li data-target="#carousel" data-slide-to="1"></li>
	    <li data-target="#carousel" data-slide-to="3"></li>
	    <li data-target="#carousel" data-slide-to="4"></li>
  	</ol> -->

</div>