	<div id="copyright-wrapper" class="fixed-footer">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<p>© 2015 Blink Design Group. All Rights Reserved.</p>					
					<p>No part of this website, designs, layouts or any of its contents may be reproduced, copied, modified or adapted, without the prior written consent of Blink Design Group.</p>
				</div>
			</div>
		</div>
	</div>
	<footer id="footer-wrapper" class="fixed-footer"><!-- container-fluid -->
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="pull-left tweet">
						<p><i class="fa fa-twitter"></i> @Interiordesign: Blink Design Group on what it's like working for legends of luxury. @Blinkdesigngroup</p>
					</div>
					<div class="pull-right sharing">
						<a href="#">#Blinkdesigngroup</a>
						<ul>
							<li><a href="#"><i class="fa fa-facebook"></i></a></li>
							<li><a href="#"><i class="fa fa-twitter"></i></a></li>
							<li><a href="#"><i class="fa fa-instagram"></i></a></li>
							<li><a href="#"><i class="fa fa-pinterest-p"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</footer>
</div><!-- page wrapper end -->