<div id="menu-logo-wrapper" class="animated slideInDown">
	<!-- <div class="container">
		<div class="row">
			<div class="col-md-12"> -->
			<div class="main-menu">
				<a href="#" class="menu toggleMenu pull-left"><i class="fa fa-bars"></i> MENU</a>
				<a href="index.html" class="logo pull-right">bdg</a>
			</div>
			<!-- </div>
		</div>
	</div> -->			
</div>

<div class="sidebar-nav animated">
	<ul class="main-nav">
		<li><a href="#">About Us</a></li>
		<li><a href="#">Featured</a></li>
		<li>
			<a href="#">Projects</a>
			<ul class="sub-nav">
				<li><a href="#">Retail</a></li>
				<li><a href="#">Food & Beverage</a></li>
				<li><a href="#">Hotel & Resort</a>
					<ul class="sub-nav-child">
						<li><a href="#">Jumeirah Dhevanfushi </a></li>
						<li><a href="#">Fairmont Sanur</a></li>
						<li><a href="#">Regent Taipei</a></li>
						<li><a href="#">Regent Phuket </a></li>
						<li><a href="#">Cape Panwa </a></li>
						<li><a href="#">Conrad Sanya </a></li>
						<li><a href="#">Haitang Bay </a></li>
						<li><a href="#">Rosewood </a></li>
						<li><a href="#">Clearwater Bay </a></li>
						<li><a href="#">Alila Salalah</a></li>
						<li><a href="#">Princes’ Palace </a></li>
						<li><a href="#">Resort & Spa </a></li>
						<li><a href="#">Kempinski KL</a></li>
						<li><a href="#">Regent Place Xi’An</a></li>
						<li><a href="#">Regent Jakarta</a></li>
						<li><a href="#">Six Senses </a></li>
						<li><a href="#">Uluwatu</a></li>
					</ul>
				</li>
				<li><a href="#">Residential</a></li>
				<li><a href="#">Commercial</a></li>
			</ul>
		</li>
		<li><a href="#">Clients</a></li>
		<li><a href="#">News</a></li>
		<li><a href="#">Careers</a></li>
		<li><a href="#">Contact</a></li>
	</ul>				
</div>